site_name: Fluxtion stream processing
site_description: Data stream processing library for Java
site_url: https://telaminai.github.io/fluxtion/
repo_url: https://github.com/telaminai/fluxtion
repo_name: telaminai/fluxtion
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: blue
      accent: indigo

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - attr_list
  - tables

plugins:
  - search
  - mermaid2
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telaminai
  # Define variables here
  fluxtion_src_runtime: https://github.com/telaminai/fluxtion/tree/main/fluxtion-runtime/src/main/java/com/telamin/fluxtion/runtime
  fluxtion_example_src: https://github.com/telaminai/fluxtion-examples/tree/main
  fluxtion_version: 0.9.6
  release_date: "2024-09-13"

nav:
  - Home:
      - Index: index.md
      - Why fluxtion: home/why-fluxtion.md
      - Choosing fluxtion: home/choosing-fluxtion.md
      - Concepts and architecture: home/concepts-and-architecture.md
      - Event dispatch: home/event-dispatch-diagrams.md
      - Dataflow programming: home/what-is-dataflow.md
      - For engineers: home/intro-engineers.md
      - For managers: home/intro-managers.md
      - Fundamentals: home/dataflow-fundamentals.md
  - Getting started:
      - 1 minute tutorial: getting-started/quickstart.md
      - Tutorial part‑1: getting-started/tutorial-part-1.md
      - Tutorial part‑2: getting-started/tutorial-part-2.md
      - Tutorial part‑3: getting-started/tutorial-part-3.md
      - Tutorial part‑4: getting-started/tutorial-part-4.md
      - Tutorial part‑5: getting-started/tutorial-part-5.md
  - Examples and how-to:
      - Example repo: example/examples.md
  - Troubleshooting: troubleshooting/index.md
  - Reference guide:
      - Quick reference: reference/reference-documentation.md
      - Console sink formatting: reference/console-sink-format.md
      - DSL Dataflow:
          - DSL introduction: reference/functional/overview-functional.md
          - DSL core: reference/functional/dataflow-functional-dsl.md
          - DSL trigger control: reference/functional/trigger-control.md
          - DSL aggregating: reference/functional/aggregating.md
          - DSL windowing: reference/functional/windowing.md
          - DSL groupBy: reference/functional/dataflow-functional-groupby-dsl.md
      - Imperative Dataflow:
          - Overview: reference/imperative/index.md
          - Basics: reference/imperative/basics.md
          - Filtering: reference/imperative/filtering.md
          - Triggering: reference/imperative/triggering.md
          - Callbacks: reference/imperative/callbacks.md
          - Trigger reference: reference/imperative/trigger-reference.md
          - Advanced: reference/imperative/advanced.md
          - Lifecycle callbacks: reference/imperative/lifecycle-callbacks.md
      - Combine DSL and imperative: reference/connecting-dsl-imperative.md
      - API javadoc:
        - Fluxtion-runtime: https://javadoc.io/doc/com.telamin.fluxtion/fluxtion-runtime/latest/index.html
        - Fluxtion-builder: https://javadoc.io/doc/com.telamin.fluxtion/fluxtion-builder/latest/index.html
