site_name: Fluxtion stream processing
site_description: Data stream processing library for Java
site_url: https://telaminai.github.io/fluxtion/
repo_url: https://github.com/telaminai/fluxtion
repo_name: telaminai/fluxtion
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      primary: blue
      accent: indigo

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - attr_list
  - tables

plugins:
  - search
  - mermaid2
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/telaminai
  # Define variables here
  fluxtion_src_runtime: https://github.com/telaminai/fluxtion/tree/main/fluxtion-runtime/src/main/java/com/telamin/fluxtion/runtime
  fluxtion_example_src: https://github.com/telaminai/fluxtion-examples/tree/main
  fluxtion_version: 0.9.11
  release_date: "2025-10-10"

nav:
  - Home:
      - Index: index.md
      - Why fluxtion: home/why-fluxtion.md
      - Choosing fluxtion: reference/choosing-fluxtion.md
      - Concepts and architecture: home/concepts-and-architecture.md
      - For engineers: home/intro-engineers.md
      - For managers: home/intro-managers.md
  - Getting started:
      - 1 minute tutorial: getting-started/quickstart.md
      - Sample application: sample-apps/embedding-dataflow-file-feed-sink-demo.md
      - Tutorials:
        - Tutorial filer/map/groupBy: getting-started/tutorial-part-1.md
        - Tutorial windows, aggregation and outputs: getting-started/tutorial-part-2.md
        - Tutorial DSL and imperative: getting-started/tutorial-part-3.md
        - Tutorial embed in microservice: getting-started/tutorial-part-4.md
        - Tutorial poll feeds: getting-started/tutorial-part-5.md
  - Examples and how-to:
      - Example repo: example/examples.md
      - How-to:
          - Log4j2 setup: how-to/logging-setup.md
          - Junit testing: how-to/unit-testing-dataflow.md
          - State and recovery: how-to/state-and-recovery.md
          - Record and replay: how-to/replay-functionality.md
          - Creating an EventFeedAgent: example/event-feed-agent.md
  - Fluxtion programming:
      - Functional DSL Dataflow:
          - DSL introduction: reference/functional/overview-functional.md
          - DSL core: reference/functional/dataflow-functional-dsl.md
          - DSL trigger control: reference/functional/trigger-control.md
          - DSL aggregating: reference/functional/aggregating.md
          - DSL windowing: reference/functional/windowing.md
          - DSL groupBy: reference/functional/dataflow-functional-groupby-dsl.md
          - DSL groupBy windowed: reference/functional/windowed-groupby.md
          - DSL groupBy map/reduce: reference/functional/groupby-functional-support.md
          - DSL groupBy joining: reference/functional/joining.md
      - Imperative Dataflow:
          - Imperative introduction: reference/imperative/overview-imperative.md
          - Imperative subscribing: reference/imperative/basics.md
          - Imperative filtering: reference/imperative/filtering.md
          - Imperative triggering: reference/imperative/triggering.md
          - Imperative callbacks: reference/imperative/callbacks.md
          - Imperative trigger override: reference/imperative/trigger-reference.md
          - Imperative advanced: reference/imperative/advanced.md
          - Imperative lifecycle callbacks: reference/imperative/lifecycle-callbacks.md
      - Combine DSL and imperative: reference/connecting-dsl-imperative.md
      - Services:
          - Service introduction: reference/service/introduction.md
          - Service import: reference/service/service-registered.md
          - Service export: reference/service/service-export.md
      - Dataflow runtime:
          - Runtime introduction: runtime/runtime-overview.md
          - DataFlow context: runtime/dataflow-context.md
          - Clocks and time: runtime/clocks-and-time.md
          - Buffer and trigger: runtime/buffer-and-trigger.md
  - Integrations:
      - DataFlow connector: integration/dataflow-connector.md
  - Reference guide:
      - Quick reference: reference/reference-documentation.md
      - Architecture and design:
        - Dataflow overview: reference/what-is-dataflow.md
        - Event dispatch: reference/event-dispatch-diagrams.md
        - Fundamentals: reference/dataflow-fundamentals.md
      - Performance results: reference/performance.md
      - Reference:
          - Alternative comparisons: reference/alternative-comparisons.md
          - Console sink formatting: reference/console-sink-format.md
          - Troubleshooting: troubleshooting/troubleshooting_index.md
          - API javadoc:
            - Fluxtion-runtime: https://javadoc.io/doc/com.telamin.fluxtion/fluxtion-runtime/latest/index.html
            - Fluxtion-builder: https://javadoc.io/doc/com.telamin.fluxtion/fluxtion-builder/latest/index.html
