/*
 * SPDX-File Copyright: © 2025.  Gregory Higgins <greg.higgins@v12technology.com>
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package com.fluxtion.dataflow.runtime.audit;

/**
 * A target for a {@link LogRecord} generated by the {@link EventLogManager}. A
 * LogRecordListener is responsible for publishing the {@link LogRecord}.
 *
 * @author Greg Higgins (greg.higgins@v12technology.com)
 */
public interface LogRecordListener {

    void processLogRecord(LogRecord logRecord);
}
