/*
 * Copyright: © 2025. Gregory Higgins <greg.higgins@v12technology.com>
 * SPDX-License-Identifier: AGPL-3.0-only OR SSPL-1.0
 */
package com.telamin.fluxtion.runtime.audit;

/**
 * A target for a {@link LogRecord} generated by the {@link EventLogManager}. A
 * LogRecordListener is responsible for publishing the {@link LogRecord}.
 *
 * @author Greg Higgins (greg.higgins@v12technology.com)
 */
public interface LogRecordListener {

    void processLogRecord(LogRecord logRecord);
}
